apiVersion: batch/v1
kind: Job
metadata:
  name: ansible-ee-webhook-job-{{ uuidv4 }}
spec:
  parallelism: 1
  completions: 1
  template:
    metadata:
      name: ansible-ee-webhook-job
    spec:
      containers:
      - name: ansible-ee-webhook-job
        image: gempesaw/curl-jq
        env:
        - name: GITHUB_WEBHOOK_API_TOKEN
          valueFrom:
            secretKeyRef:
              key: BEARER_TOKEN
              name: github-webhook-api-token
        - name: EVENT_LISTENER_SECRET_TOKEN
          valueFrom:
            secretKeyRef:
              key: secretToken
              name: ansible-ee-trigger-secret
        - name: GITHUB_ORGANIZATION
          value: "{{ .Values.github.org }}"
        - name: GITHUB_REPO
          value: "{{ .Values.github.repo }}"
        - name: APPS_DOMAIN
          value: "{{ .Values.openshift.appsDomain }}"
        - name: NAMESPACE
          value: "{{ .Values.namespace }}"
        command:
        - /bin/sh
        - -c
        - |
          result=$(curl -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $GITHUB_WEBHOOK_API_TOKEN" https://api.github.com/repos/$GITHUB_ORGANIZATION/$GITHUB_REPO/hooks)
          BODY={\"name\":\"web\",\"active\":true,\"events\":[\"push\"],\"config\":{\"url\":\"http://ansible-ee-el-$NAMESPACE.$APPS_DOMAIN\",\"secret\":\"$EVENT_LISTENER_SECRET_TOKEN\",\"content_type\":\"json\",\"insecure_ssl\":\"0\"}}
          if [[ $(echo $result | (jq '. | length')) == 0 ]]; then curl -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $GITHUB_WEBHOOK_API_TOKEN" https://api.github.com/repos/$GITHUB_ORGANIZATION/$GITHUB_REPO/hooks -d $BODY; fi
      restartPolicy: Never